"""Config presets for proto_ssm_config_sweep.py.

Each entry is consumed by train_light_proto_ssm via proto_ssm_config_sweep.py.
"""

_BASE_MODELS = [
    {
        "name": "xl_attn_d192_s24",
        "n_epochs": 50,
        "patience": 10,
        "lr": 8e-4,
        "n_sites": 20,
        "d_model": 192,
        "d_state": 24,
        "n_ssm_layers": 2,
        "dropout": 0.15,
        "meta_dim": 24,
        "distill_weight": 0.15,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.65,
        "swa_lr": 3e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 4,
    },
    {
        "name": "xl_attn_d224_s24",
        "n_epochs": 50,
        "patience": 10,
        "lr": 8e-4,
        "n_sites": 20,
        "d_model": 224,
        "d_state": 24,
        "n_ssm_layers": 2,
        "dropout": 0.15,
        "meta_dim": 24,
        "distill_weight": 0.15,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.65,
        "swa_lr": 3e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 4,
    },
    {
        "name": "xxl_attn_d256_s32",
        "n_epochs": 60,
        "patience": 12,
        "lr": 7e-4,
        "n_sites": 20,
        "d_model": 256,
        "d_state": 32,
        "n_ssm_layers": 3,
        "dropout": 0.18,
        "meta_dim": 32,
        "distill_weight": 0.18,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.70,
        "swa_lr": 3e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 4,
    },
    {
        "name": "xxl_attn_d288_s32",
        "n_epochs": 60,
        "patience": 12,
        "lr": 7e-4,
        "n_sites": 20,
        "d_model": 288,
        "d_state": 32,
        "n_ssm_layers": 3,
        "dropout": 0.20,
        "meta_dim": 32,
        "distill_weight": 0.20,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.70,
        "swa_lr": 3e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 4,
    },
    {
        "name": "xxxl_attn_d320_s32",
        "n_epochs": 65,
        "patience": 14,
        "lr": 6e-4,
        "n_sites": 20,
        "d_model": 320,
        "d_state": 32,
        "n_ssm_layers": 3,
        "dropout": 0.22,
        "meta_dim": 40,
        "distill_weight": 0.20,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.72,
        "swa_lr": 2.5e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 8,
    },
    {
        "name": "xxxl_attn_d384_s32",
        "n_epochs": 70,
        "patience": 14,
        "lr": 6e-4,
        "n_sites": 20,
        "d_model": 384,
        "d_state": 32,
        "n_ssm_layers": 4,
        "dropout": 0.25,
        "meta_dim": 48,
        "distill_weight": 0.22,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.72,
        "swa_lr": 2.5e-4,
        "use_cross_attn": True,
        "cross_attn_heads": 8,
    },
    {
        "name": "wide_noattn_d256_s24",
        "n_epochs": 55,
        "patience": 10,
        "lr": 8e-4,
        "n_sites": 20,
        "d_model": 256,
        "d_state": 24,
        "n_ssm_layers": 3,
        "dropout": 0.15,
        "meta_dim": 24,
        "distill_weight": 0.15,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.68,
        "swa_lr": 3e-4,
        "use_cross_attn": False,
        "cross_attn_heads": 2,
    },
    {
        "name": "wide_noattn_d320_s32",
        "n_epochs": 60,
        "patience": 12,
        "lr": 7e-4,
        "n_sites": 20,
        "d_model": 320,
        "d_state": 32,
        "n_ssm_layers": 4,
        "dropout": 0.18,
        "meta_dim": 32,
        "distill_weight": 0.18,
        "pos_weight_cap": 25.0,
        "use_swa": True,
        "swa_start_frac": 0.70,
        "swa_lr": 2.5e-4,
        "use_cross_attn": False,
        "cross_attn_heads": 2,
    },
]


def _clone(base: dict, suffix: str, **updates: object) -> dict:
    cfg = dict(base)
    cfg.update(updates)
    cfg["name"] = f"{base['name']}_{suffix}"
    return cfg


PROTO_SSM_SWEEP_CONFIGS = []

# Keep the original-style baseline configs.
PROTO_SSM_SWEEP_CONFIGS.extend(_BASE_MODELS)

# Large and extreme baselines.
PROTO_SSM_SWEEP_CONFIGS.extend(
    [
        {
            "name": "ultra_attn_d448_s40",
            "n_epochs": 75,
            "patience": 15,
            "lr": 5e-4,
            "n_sites": 24,
            "d_model": 448,
            "d_state": 40,
            "n_ssm_layers": 4,
            "dropout": 0.28,
            "meta_dim": 56,
            "distill_weight": 0.22,
            "pos_weight_cap": 30.0,
            "use_swa": True,
            "swa_start_frac": 0.75,
            "swa_lr": 2e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 8,
        },
        {
            "name": "ultra_attn_d512_s48",
            "n_epochs": 80,
            "patience": 16,
            "lr": 5e-4,
            "n_sites": 24,
            "d_model": 512,
            "d_state": 48,
            "n_ssm_layers": 4,
            "dropout": 0.30,
            "meta_dim": 64,
            "distill_weight": 0.25,
            "pos_weight_cap": 30.0,
            "use_swa": True,
            "swa_start_frac": 0.75,
            "swa_lr": 2e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 8,
        },
    ]
)

# Systematic stress variants from the first 10 entries.
_SEED_SET = list(PROTO_SSM_SWEEP_CONFIGS[:10])
for base in _SEED_SET:
    PROTO_SSM_SWEEP_CONFIGS.append(
        _clone(
            base,
            "nodistill_noswa",
            distill_weight=0.0,
            use_swa=False,
            swa_start_frac=1.1,
            swa_lr=0.0,
        )
    )
    PROTO_SSM_SWEEP_CONFIGS.append(
        _clone(
            base,
            "nodistill_swa",
            distill_weight=0.0,
            use_swa=True,
            swa_start_frac=min(float(base.get("swa_start_frac", 0.7)), 0.7),
            swa_lr=float(base.get("swa_lr", 3e-4)),
        )
    )
    PROTO_SSM_SWEEP_CONFIGS.append(
        _clone(
            base,
            "highdistill",
            distill_weight=0.5,
            use_swa=True,
            swa_start_frac=min(float(base.get("swa_start_frac", 0.7)), 0.6),
            swa_lr=max(float(base.get("swa_lr", 3e-4)) * 0.8, 1.5e-4),
        )
    )
    PROTO_SSM_SWEEP_CONFIGS.append(
        _clone(
            base,
            "noswa_fastlr",
            use_swa=False,
            swa_start_frac=1.1,
            swa_lr=0.0,
            lr=float(base.get("lr", 7e-4)) * 1.35,
            patience=max(6, int(base.get("patience", 10)) - 2),
        )
    )

# Additional aggressive architecture variants.
PROTO_SSM_SWEEP_CONFIGS.extend(
    [
        {
            "name": "tiny_noattn_d128_s16_l1_nodistill_noswa",
            "n_epochs": 45,
            "patience": 8,
            "lr": 1.2e-3,
            "n_sites": 20,
            "d_model": 128,
            "d_state": 16,
            "n_ssm_layers": 1,
            "dropout": 0.10,
            "meta_dim": 16,
            "distill_weight": 0.0,
            "pos_weight_cap": 20.0,
            "use_swa": False,
            "swa_start_frac": 1.1,
            "swa_lr": 0.0,
            "use_cross_attn": False,
            "cross_attn_heads": 2,
        },
        {
            "name": "tiny_attn_d160_s16_l2_nodistill",
            "n_epochs": 50,
            "patience": 9,
            "lr": 1.0e-3,
            "n_sites": 20,
            "d_model": 160,
            "d_state": 16,
            "n_ssm_layers": 2,
            "dropout": 0.12,
            "meta_dim": 20,
            "distill_weight": 0.0,
            "pos_weight_cap": 22.0,
            "use_swa": True,
            "swa_start_frac": 0.65,
            "swa_lr": 3.5e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 4,
        },
        {
            "name": "deep_attn_d256_s24_l6",
            "n_epochs": 70,
            "patience": 14,
            "lr": 6e-4,
            "n_sites": 24,
            "d_model": 256,
            "d_state": 24,
            "n_ssm_layers": 6,
            "dropout": 0.22,
            "meta_dim": 32,
            "distill_weight": 0.12,
            "pos_weight_cap": 30.0,
            "use_swa": True,
            "swa_start_frac": 0.70,
            "swa_lr": 2.5e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 8,
        },
        {
            "name": "deep_noattn_d320_s32_l6_noswa",
            "n_epochs": 70,
            "patience": 12,
            "lr": 7.5e-4,
            "n_sites": 24,
            "d_model": 320,
            "d_state": 32,
            "n_ssm_layers": 6,
            "dropout": 0.20,
            "meta_dim": 36,
            "distill_weight": 0.08,
            "pos_weight_cap": 30.0,
            "use_swa": False,
            "swa_start_frac": 1.1,
            "swa_lr": 0.0,
            "use_cross_attn": False,
            "cross_attn_heads": 2,
        },
        {
            "name": "ultra_attn_d640_s64_l5_extreme",
            "n_epochs": 90,
            "patience": 18,
            "lr": 3.5e-4,
            "n_sites": 28,
            "d_model": 640,
            "d_state": 64,
            "n_ssm_layers": 5,
            "dropout": 0.32,
            "meta_dim": 72,
            "distill_weight": 0.30,
            "pos_weight_cap": 35.0,
            "use_swa": True,
            "swa_start_frac": 0.78,
            "swa_lr": 1.5e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 8,
        },
        {
            "name": "ultra_noattn_d640_s64_l5_nodistill_noswa",
            "n_epochs": 85,
            "patience": 14,
            "lr": 5.5e-4,
            "n_sites": 28,
            "d_model": 640,
            "d_state": 64,
            "n_ssm_layers": 5,
            "dropout": 0.28,
            "meta_dim": 72,
            "distill_weight": 0.0,
            "pos_weight_cap": 35.0,
            "use_swa": False,
            "swa_start_frac": 1.1,
            "swa_lr": 0.0,
            "use_cross_attn": False,
            "cross_attn_heads": 2,
        },
        {
            "name": "high_lr_attn_d224_s24",
            "n_epochs": 45,
            "patience": 7,
            "lr": 1.6e-3,
            "n_sites": 20,
            "d_model": 224,
            "d_state": 24,
            "n_ssm_layers": 2,
            "dropout": 0.18,
            "meta_dim": 24,
            "distill_weight": 0.10,
            "pos_weight_cap": 22.0,
            "use_swa": False,
            "swa_start_frac": 1.1,
            "swa_lr": 0.0,
            "use_cross_attn": True,
            "cross_attn_heads": 4,
        },
        {
            "name": "low_lr_attn_d384_s32",
            "n_epochs": 90,
            "patience": 18,
            "lr": 2.5e-4,
            "n_sites": 24,
            "d_model": 384,
            "d_state": 32,
            "n_ssm_layers": 4,
            "dropout": 0.22,
            "meta_dim": 48,
            "distill_weight": 0.18,
            "pos_weight_cap": 30.0,
            "use_swa": True,
            "swa_start_frac": 0.80,
            "swa_lr": 1.2e-4,
            "use_cross_attn": True,
            "cross_attn_heads": 8,
        },
    ]
)
